### ISSUE TITLE
NullPointerException: null on ChunkUnloadListener

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#54]
```
[05:55:57] [Craft Scheduler Thread - 745/WARN]: [ArtMap] Plugin ArtMap v2.6.7 generated an exception while executing task 852469
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.jar:git-Paper-1133]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.jar:git-Paper-1133]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.jar:git-Paper-1133]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[06:42:56] [Craft Scheduler Thread - 809/WARN]: [ArtMap] Plugin ArtMap v2.6.7 generated an exception while executing task 1029037
java.lang.NullPointerException: null
```

**Comment by Fupery** [comment]
Should be fixed in ArtMap 2.6.11 - let me know if it isn't!

**Comment by mibby** [comment]
@Fupery Still an issue as of commit https://github.com/Fupery/ArtMap/commit/28e08a1c30e60648264a62e28e22de0e23c33aee unfortunately.

```
[10:05:33] [Craft Scheduler Thread - 759/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 131888
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.jar:git-Paper-1143]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.jar:git-Paper-1143]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.jar:git-Paper-1143]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by mibby** [comment]
```
[13:12:32] [Craft Scheduler Thread - 390/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 1544888
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.jar:git-Paper-1167]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.jar:git-Paper-1167]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.jar:git-Paper-1167]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by mibby** [comment]
Bump. :(

```
[23:57:37] [Craft Scheduler Thread - 35/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 9198
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.1.jar:git-Paper-1190]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1190]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1190]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by mibby** [comment]
@Fupery Still a presently existing issue. :(

```
[22:20:55] [Craft Scheduler Thread - 119/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 238757
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.1.jar:git-Paper-1196]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1196]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[22:20:55] [Craft Scheduler Thread - 114/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 238751
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.1.jar:git-Paper-1196]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1196]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[22:20:55] [Craft Scheduler Thread - 115/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 238756
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.1.jar:git-Paper-1196]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1196]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[22:20:55] [Craft Scheduler Thread - 122/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 238755
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.1.jar:git-Paper-1196]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1196]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[22:20:55] [Craft Scheduler Thread - 106/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 238759
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.1.jar:git-Paper-1196]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1196]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[22:20:55] [Craft Scheduler Thread - 109/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 238749
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.1.jar:git-Paper-1196]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1196]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[22:20:55] [Craft Scheduler Thread - 129/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 238753
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.1.jar:git-Paper-1196]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1196]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[22:20:55] [Craft Scheduler Thread - 118/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 238758
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.1.jar:git-Paper-1196]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1196]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by mibby** [comment]
@Fupery Still happening Fupery. :( Any chances on you looking into the issue again, as well as the deprecated API one?

```
[12:57:27] [Craft Scheduler Thread - 221/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 296221
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[ArtMap.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1272]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1272]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1272]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by mibby** [comment]
It doesn't seem to be.. :(
```
[12:18:37] [Craft Scheduler Thread - 340/WARN]: [ArtMap] Plugin ArtMap v2.6.11 generated an exception while executing task 483371
java.lang.NullPointerException: null
	at me.Fupery.ArtMap.Listeners.ChunkUnloadListener.lambda$onChunkUnload$0(ChunkUnloadListener.java:21) ~[ArtMap.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1329]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1329]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```
